name: Compress Repository

on:
  push:
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Increment Version Number
        run: |
          # Read and increment version number in manifest.json
          version=$(jq -r '.version_number' manifest.json)
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          jq --arg new_version "$new_version" '.version_number = $new_version' manifest.json > temp.json && mv temp.json manifest.json
          
          # Display updated version for confirmation
          cat manifest.json

      - name: Zip Repository
        run: |
          zip -r repo_archive.zip . -x ".git/*" ".github/*" "EGKLethalGamers.zip"
          mv repo_archive.zip ./EGKLethalGamers.zip

      - name: Commit and Push Zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epicGamerPak.zip
          git add manifest.json
          git commit -m "Automated repository compression" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
